spring:
  application:
    name: account-book
  config:
    activate:
      on-profile: prd
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: ENC(5GkOYYQH8zzOLn8ke4IMKdXlLwP/1Cr+W8nxA/uXF4V6bevHIQlkGVPTzfyVnELGntEgh1jrbsuDWWe/tMd2R1DBl45D2hXnPYoAvPj0PaKtZXxBlBI2su28KwyQQ4FlMSssLUKQGJH/7xBXIsWogT2WtXCYLxPrQEM3yZ6WmT0=)
    username: ENC(VoOM+YniWoF6oxcrkjmySGAHRe5TU2Gqg4k9VNjdZnMWaS+Zn5FI6qypfEYfObEB)
    password: ENC(cHv+WoCaY18rpm5wdCHB79J5WpqCSHd2iMmdWC92IY1jCPOooK5zT3NZC8Sary5Z)
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: false
        show_sql: false
        jdbc:
          batch_size: 1000
  security:
    white-list:
      - /api/v1/authenticate  # 로그인
      - /api/v1/reissue/token # 토큰 재발행
      - /api/v1/signup        # 회원가입
      - /api/v1/verify        # email 인증
      - /favicon.ico          # 파비콘
      - /error                # 에러
      - /h2-console           # h2-console

cors:
  allowed:
    origins:
      - https://booroute.com
    headers:
      - Origin
      - X-Requested-with
      - Accept
      - Authorization
      - Content-Type
      - Credential-Token
      - Access-Token
      - Refresh-Token
      - Access-Control-Allow-Headers
      - Access-Control-Allow-Origin
      - Access-Control-Request-Method
      - Access-Control-Request-Headers


jwt:
  access-token-expiration-time: 1800 # 30분
  refresh-token-expiration-time: 2592000 # 30일

aws:
  ses:
    use: false
    sender: mail.booroute@gmail.com
    region: ap-northeast-2
    # key:
    #  access: at-arg
    #  secret: at-arg

logging:
  level:
    com.bb.com.bb.accountbook.common.log: info
    com.bb.accountbook: error
    org.springframework: error
    org.hibernate:
      type:
        descriptor.sql: error
    p6spy: error

jasypt:
  encryptor:
    bean: jasyptEncryptorAES