spring:
  application:
    name: account-book
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true
        jdbc:
          batch_size: 1000
  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    white-list:
      - /api/v1/authenticate  # 회원가입
      - /api/v1/signup        # 로그인
      - /favicon.ico          # 파비콘
      - /error                # 에러
      - /h2-console           # h2-console

cors:
  allowed:
    origins:
      - http://localhost:3000
      - http://booroute.com
      - https://booroute.com
    headers:
      - Origin
      - X-Requested-with
      - Accept
      - Authorization
      - Content-Type
      - Credential-Token
      - Access-Token
      - Refresh-Token
      - Access-Control-Allow-Headers
      - Access-Control-Allow-Origin
      - Access-Control-Request-Method
      - Access-Control-Request-Headers


jwt:
  secret: secret1234secret1234secret1234secret1234secret1234secret1234secret1234secret1234secret1234secret1234secret1234secret1234
  access-token-expiration-time: 1800 # 30분
  refresh-token-expiration-time: 1209600 # 14일
  iss: hay-account-book



email:
  official:
    email: k941026h@naver.com
    password: 12341234

logging:
  level:
    org.springframework: debug
    org.hibernate:
      type:
        descriptor.sql: trace