spring:
  application:
    name: account-book
  datasource:
    url: jdbc:h2:mem:testdb;MODE=Oracle
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true
        jdbc:
          batch_size: 1000
  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    white-list:
      - /api/v1/authenticate  # 로그인
      - /api/v1/reissue/token # 토큰 재발행
      - /api/v1/signup        # 회원가입
      - /api/v1/verify        # email 인증
      - /api/admin/v1/authenticate  # admin 로그인
      - /favicon.ico          # 파비콘
      - /error                # 에러
      - /h2-console           # h2-console

cors:
  allowed:
    origins:
      - http://localhost:63342
      - http://localhost:3000
      - http://booroute.com
      - https://booroute.com
    headers:
      - Origin
      - X-Requested-with
      - Accept
      - Authorization
      - Content-Type
      - Credential-Token
      - Access-Token
      - Refresh-Token
      - Access-Control-Allow-Headers
      - Access-Control-Allow-Origin
      - Access-Control-Request-Method
      - Access-Control-Request-Headers


jwt:
  secret: local1234local1234local1234local1234local1234local1234local1234local1234local1234local1234local1234local1234
  access-token-expiration-time: 20 # 15초
  refresh-token-expiration-time: 1209600 # 14일
  iss: local-iss

aws:
  ses:
    use: false
    sender: mail.booroute@gmail.com
    region: ap-northeast-2
    key:
      access: at-arg
      secret: at-arg

key:
  rsa:
    private: local-private-key
    public: local-public-key

logging:
  level:
    com.bb.accountbook.common.log: info
    com.bb.accountbook: debug
    org.springframework: debug
    org.hibernate:
      type:
        descriptor.sql: trace
